import * as vscode from 'vscode';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { parseStl } from './stl';
import { sliceVase, DEFAULT_OPTIONS } from './vase';
import { clampOverhangs } from './clamp';
import { runOrca, extractGcodeFrom3mf, OrcaConfig } from './orca';
import { listZipEntries, findEntry } from './zip';
import { packBambu3mf } from './bambu';

export function activate(context: vscode.ExtensionContext) {
  let panel: vscode.WebviewPanel | undefined;
  let trackedUri: vscode.Uri | undefined;
  let debounce: ReturnType<typeof setTimeout> | undefined;
  let watcher: fs.FSWatcher | undefined;
  let watchDebounce: ReturnType<typeof setTimeout> | undefined;
  let watchTarget: string | undefined; // exact file being watched (may not exist yet)
  let watchNewestIn: string | undefined; // or: follow the newest g-code in this folder
  let watchStatus: vscode.StatusBarItem | undefined;

  // Reads the tracked file's current content — from the open editor if it's
  // open, otherwise straight from disk (so external tools like Orca refresh it).
  // `desdeDisco` salta el documento abierto en el editor. Hace falta después de
  // regenerar: si el .gcode está abierto en una pestaña, `doc.getText()` devuelve
  // la copia en memoria de VS Code, que sigue siendo la vieja hasta que el
  // editor note el cambio — así que el generador corría bien y el preview
  // seguía mostrando la pieza anterior.
  // `toquesAplicados` es la lista con la que se generó ESTE texto. Solo la manda
  // quien lo sabe de verdad: la regeneración, que la lee justo antes de lanzar
  // Python. Los demás caminos —guardar el archivo, teclear, cambiar de editor—
  // la omiten, y el preview entonces no toca su estado.
  //
  // Adivinarlo del lado del webview («lo último que mandé») fallaba: cualquier
  // mensaje de g-code que llegara ANTES de que Python terminara daba por
  // horneados unos toques que el archivo todavía no tenía, la resta se iba a
  // cero y la pieza saltaba a la forma vieja hasta la recarga.
  async function sendDoc(desdeDisco = false, toquesAplicados?: any[]) {
    if (!panel || !trackedUri) {
      return;
    }
    const doc = desdeDisco ? undefined : vscode.workspace.textDocuments.find(
      (d) => d.uri.toString() === trackedUri!.toString()
    );
    let text = '';
    if (doc) {
      text = doc.getText();
    } else {
      try {
        text = new TextDecoder().decode(await vscode.workspace.fs.readFile(trackedUri));
      } catch {
        text = '';
      }
    }
    // Qué archivo es, para que el preview sepa si esto es una pieza nueva —y
    // hay que encuadrarla— o la misma de siempre regenerada, donde mover la
    // cámara sería sacarle al usuario el punto de vista que eligió.
    panel.webview.postMessage({
      type: 'gcode', text, ruta: trackedUri.toString(), toquesAplicados
    });
  }

  function ensurePanel() {
    if (panel) {
      return;
    }
    panel = vscode.window.createWebviewPanel(
      'gcodePreview',
      'G-code Preview',
      vscode.ViewColumn.Beside,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [vscode.Uri.joinPath(context.extensionUri, 'media')]
      }
    );
    panel.webview.html = getHtml(panel.webview, context.extensionUri);
    panel.onDidDispose(
      () => {
        panel = undefined;
      },
      null,
      context.subscriptions
    );
    // The webview tells us when it has booted and is ready to receive data.
    panel.webview.onDidReceiveMessage(
      (msg) => {
        if (msg && msg.type === 'ready') {
          // La receta ANTES que el g-code: trae el mapeo z↔t, y el webview lo
          // necesita ya para colocar cada vértice en su altura relativa. Al
          // revés, la primera pieza que se abre usa el mapeo lineal de respaldo.
          sendRecipe();
          sendDoc();
          enviarPlantilla();
        } else if (msg && msg.type === 'plantilla') {
          void bambuTemplate(true);
        } else if (msg && msg.type === 'regen') {
          void regenerate(msg.valores || {}, !!msg.borrador);
        } else if (msg && msg.type === 'toques') {
          void guardarToques(msg.toques || []).then(
            () => regenerate(msg.valores || {}, !!msg.borrador)
          );
        } else if (msg && msg.type === 'guardar') {
          void guardarReceta();
        } else if (msg && msg.type === 'cargar') {
          void cargarReceta();
        } else if (msg && msg.type === 'orca') {
          void abrirEnOrca();
        }
      },
      undefined,
      context.subscriptions
    );
  }

  // --- Parametric controls --------------------------------------------------
  // A g-code file generated by the FullControl scripts has a `<name>.params.json`
  // beside it recording the exact command that produced it. That is what lets
  // this panel offer sliders: read the recipe, show one control per numeric
  // parameter, and on change RE-RUN the generator with the new value.
  //
  // The g-code is never edited, only regenerated. That is the whole point — an
  // edited g-code has no parameters any more, so the next run silently throws
  // the edit away, and the extrusion amounts would have to be recomputed by
  // hand for every moved point. Regenerating has neither problem.
  let receta: any = null;
  let corriendo = false;
  let pendiente: { valores: any; borrador: boolean } | null = null;

  function recipeUri(uri: vscode.Uri): vscode.Uri {
    return uri.with({ path: uri.path.replace(/\.gcode$/i, '.params.json') });
  }

  // Los toques viven en su propio archivo y no dentro de la receta: son una
  // lista que crece con cada click, y el generador los lee con `--toques`. Al
  // ser un archivo aparte también se puede editar a mano y se versiona solo.
  function toquesUri(uri: vscode.Uri): vscode.Uri {
    return uri.with({ path: uri.path.replace(/\.gcode$/i, '.toques.json') });
  }

  function leerToques(): any[] {
    if (!trackedUri) return [];
    try {
      const crudo = JSON.parse(fs.readFileSync(toquesUri(trackedUri).fsPath, 'utf8'));
      const lista = Array.isArray(crudo) ? crudo : crudo.toques;
      return Array.isArray(lista) ? lista : [];
    } catch { return []; }
  }

  function sendRecipe() {
    receta = null;
    if (trackedUri) {
      try {
        receta = JSON.parse(fs.readFileSync(recipeUri(trackedUri).fsPath, 'utf8'));
      } catch { /* sin receta: el archivo no lo generó nuestro script */ }
    }
    panel?.webview.postMessage({ type: 'recipe', receta, toques: leerToques() });
  }

  async function guardarToques(toques: any[]) {
    if (!trackedUri) return;
    const ruta = toquesUri(trackedUri);
    const cuerpo = JSON.stringify({ version: 1, toques }, null, 1);
    await vscode.workspace.fs.writeFile(ruta, Buffer.from(cuerpo, 'utf8'));
  }

  async function regenerate(valores: Record<string, number>, borrador: boolean) {
    if (!receta) return;
    // Una sola corrida a la vez; si llega otra mientras tanto, se guarda la
    // última y se corre al terminar. Arrastrar un slider dispara decenas de
    // pedidos y encolarlos todos dejaría el panel minutos atrasado.
    if (corriendo) { pendiente = { valores, borrador }; return; }
    corriendo = true;
    panel?.webview.postMessage({ type: 'regen-estado', estado: 'corriendo' });

    // Se fotografía ACÁ, que es lo que Python va a leer del disco al arrancar.
    const toquesUsados = leerToques();
    // Los flags que llevan `clave=valor` en el argumento siguiente, y que por
    // eso se sustituyen distinto que los que llevan el valor suelto.
    //
    // Es un CONJUNTO EXACTO y no un prefijo a propósito. Estaba escrito como
    // `flag.startsWith('--p')`, que además de `--p/--pe/--pp/--ps` atrapaba a
    // `--perfil-escala`, `--piso` y `--piso-refuerzo`: el flag entraba por la
    // rama de clave=valor, no encontraba el `=`, y el `else` lo rechazaba por
    // empezar con `--p`. Resultado: el slider se movía, el comando se
    // relanzaba con el valor viejo y la pieza no cambiaba nunca.
    const FLAGS_KV = new Set(['--p', '--pe', '--pp', '--ps']);
    const argv = [...receta.args];
    for (const c of receta.controles) {
      const clave = `${c.flag}:${c.clave}`;
      if (!(clave in valores)) continue;
      const v = valores[clave];
      for (let i = 0; i < argv.length - 1; i++) {
        if (argv[i] === c.flag) {
          if (FLAGS_KV.has(c.flag) && String(argv[i + 1]).startsWith(c.clave + '=')) {
            argv[i + 1] = `${c.clave}=${v}`;
          } else if (!FLAGS_KV.has(c.flag)) {
            argv[i + 1] = String(v);
          }
        }
      }
    }
    // El archivo de toques puede haber nacido DESPUÉS de la receta —la primera
    // pincelada de una pieza que no tenía ninguno—, así que el flag se agrega
    // acá y no se espera a que la receta lo traiga.
    if (trackedUri && fs.existsSync(toquesUri(trackedUri).fsPath) && !argv.includes('--toques')) {
      argv.push('--toques', toquesUri(trackedUri).fsPath);
    }
    if (borrador && Array.isArray(receta.borrador)) argv.push(...receta.borrador);

    // El intérprete puede estar del otro lado de WSL. Pasa siempre que el
    // proyecto vive en /mnt/c y VS Code se abrió como ventana nativa de Windows:
    // el host no puede ejecutar una ruta POSIX, y el error que sale ("el
    // generador falló") no dice nada de eso. Se detecta por la forma de la ruta
    // y se envuelve con `wsl.exe --cd`.
    let ejecutable: string = receta.python;
    let args: string[] = argv;
    let opciones: any = { cwd: receta.cwd };
    if (process.platform === 'win32' && receta.python.startsWith('/')) {
      ejecutable = 'wsl.exe';
      args = ['--cd', receta.cwd, '-e', receta.python, ...argv];
      opciones = {};
    }

    const ok = await new Promise<boolean>((resolve) => {
      const cp = require('child_process') as typeof import('child_process');
      const hijo = cp.spawn(ejecutable, args, opciones);
      let err = '';
      cp && hijo.stderr?.on('data', (d: Buffer) => { err += d.toString(); });
      hijo.on('error', () => resolve(false));
      hijo.on('close', (code: number) => {
        if (code !== 0) {
          vscode.window.showErrorMessage(
            `G-code: el generador falló (${ejecutable}) — ` + (err.trim().split('\n').pop() || 'sin salida')
          );
        }
        resolve(code === 0);
      });
    });

    corriendo = false;
    if (ok) void sendDoc(true, toquesUsados);
    panel?.webview.postMessage({ type: 'regen-estado', estado: 'listo' });
    if (pendiente) { const q = pendiente; pendiente = null; void regenerate(q.valores, q.borrador); }
  }

  // Guarda una copia de la pieza y de sus parámetros en `recetas/<nombre>/<etiqueta>/`.
  //
  // Las rutas salen del URI del .gcode abierto, NO de `receta.cwd`: ese último
  // es una ruta POSIX cuando el generador vive en WSL, y el host —que puede ser
  // Windows— no puede escribir ahí. El URI en cambio ya es del lado correcto.
  //
  // `output/` está en .gitignore y `recetas/` no, así que el params.json queda
  // versionado. El .gcode se copia igual por comodidad, pero `*.gcode` lo ignora
  // en todos lados — y está bien: pesa 11 MB y se reconstruye entero desde el
  // params.json, que es el punto de todo esto.
  async function guardarReceta() {
    if (!trackedUri) return;
    const gcodeUri = trackedUri;
    const recetaUri = recipeUri(gcodeUri);
    let datos: Uint8Array;
    try {
      datos = await vscode.workspace.fs.readFile(recetaUri);
    } catch {
      vscode.window.showWarningMessage(
        'G-code: este archivo no tiene .params.json al lado, no hay receta que guardar.'
      );
      return;
    }

    const base = path.posix.basename(gcodeUri.path).replace(/\.gcode$/i, '');
    const carpeta = vscode.Uri.joinPath(carpetaRecetas(gcodeUri), base);

    // Versión automática: se mira qué vNNN ya hay y se usa la siguiente. Sin
    // preguntar nada — guardar tiene que costar un click, si no deja de usarse
    // en el medio de una iteración, que es justo cuando más sirve. Nunca pisa
    // una versión anterior.
    let n = 0;
    try {
      for (const [nombre, tipo] of await vscode.workspace.fs.readDirectory(carpeta)) {
        const m = /^v(\d+)/.exec(nombre);
        if (tipo === vscode.FileType.Directory && m) n = Math.max(n, parseInt(m[1], 10));
      }
    } catch { /* todavía no hay carpeta */ }
    const etiqueta = 'v' + String(n + 1).padStart(3, '0');
    const destino = vscode.Uri.joinPath(carpeta, etiqueta);
    try {
      await vscode.workspace.fs.createDirectory(destino);
      await vscode.workspace.fs.writeFile(vscode.Uri.joinPath(destino, 'params.json'), datos);
      const g = await vscode.workspace.fs.readFile(gcodeUri);
      await vscode.workspace.fs.writeFile(vscode.Uri.joinPath(destino, base + '.gcode'), g);
      // Los toques van con la receta o la versión no reproduce la pieza: el
      // `--toques` de los args apunta a un archivo que para entonces ya cambió.
      try {
        const t = await vscode.workspace.fs.readFile(toquesUri(gcodeUri));
        await vscode.workspace.fs.writeFile(vscode.Uri.joinPath(destino, 'toques.json'), t);
      } catch { /* la pieza no tiene toques */ }
    } catch (e: any) {
      vscode.window.showErrorMessage('G-code: no se pudo guardar la receta — ' + (e?.message || e));
      return;
    }
    panel?.webview.postMessage({ type: 'guardado', donde: `recetas/${base}/${etiqueta}` });
    vscode.window.showInformationMessage(`G-code: receta guardada en recetas/${base}/${etiqueta}`);
  }

  // `.../output/x.gcode` -> `.../recetas`
  function carpetaRecetas(gcodeUri: vscode.Uri): vscode.Uri {
    const outDir = gcodeUri.with({ path: path.posix.dirname(gcodeUri.path) });
    const raiz = outDir.with({ path: path.posix.dirname(outDir.path) });
    return vscode.Uri.joinPath(raiz, 'recetas');
  }

  // Carga una versión guardada: copia su gcode y su params.json de vuelta a
  // `output/` y recarga el panel. Copiar y no abrir en su lugar es a propósito
  // — así seguís trabajando sobre `output/`, los sliders regeneran ahí como
  // siempre, y la versión guardada queda intacta por si querés volver.
  async function cargarReceta() {
    if (!trackedUri) return;
    const raizRecetas = carpetaRecetas(trackedUri);
    const opciones: { label: string; description: string; uri: vscode.Uri; base: string }[] = [];
    try {
      for (const [nombreBase, tipo] of await vscode.workspace.fs.readDirectory(raizRecetas)) {
        if (tipo !== vscode.FileType.Directory) continue;
        const dirBase = vscode.Uri.joinPath(raizRecetas, nombreBase);
        for (const [ver, t2] of await vscode.workspace.fs.readDirectory(dirBase)) {
          if (t2 !== vscode.FileType.Directory) continue;
          const dir = vscode.Uri.joinPath(dirBase, ver);
          let cuando = '';
          try {
            const st = await vscode.workspace.fs.stat(vscode.Uri.joinPath(dir, 'params.json'));
            cuando = new Date(st.mtime).toLocaleString();
          } catch { continue; } // sin params.json no es una receta
          opciones.push({ label: `${nombreBase} / ${ver}`, description: cuando, uri: dir, base: nombreBase });
        }
      }
    } catch {
      vscode.window.showWarningMessage('G-code: todavía no hay nada en recetas/.');
      return;
    }
    if (!opciones.length) {
      vscode.window.showWarningMessage('G-code: todavía no hay nada en recetas/.');
      return;
    }
    opciones.sort((a, b) => b.label.localeCompare(a.label));

    const elegida = await vscode.window.showQuickPick(opciones, {
      title: 'Cargar receta',
      placeHolder: 'Se copia a output/ y se abre en el preview'
    });
    if (!elegida) return;

    const outDir = trackedUri.with({ path: path.posix.dirname(trackedUri.path) });
    const destGcode = vscode.Uri.joinPath(outDir, elegida.base + '.gcode');
    try {
      const g = await vscode.workspace.fs.readFile(vscode.Uri.joinPath(elegida.uri, elegida.base + '.gcode'));
      const r = await vscode.workspace.fs.readFile(vscode.Uri.joinPath(elegida.uri, 'params.json'));
      await vscode.workspace.fs.writeFile(destGcode, g);
      await vscode.workspace.fs.writeFile(
        destGcode.with({ path: destGcode.path.replace(/\.gcode$/i, '.params.json') }), r
      );
      // Los toques de la versión, o ninguno: si se dejara el archivo de toques
      // que hay ahora, cargar una versión vieja traería la geometría vieja con
      // el esculpido nuevo encima, que no es ninguna de las dos piezas.
      let t: Uint8Array = Buffer.from(JSON.stringify({ version: 1, toques: [] }), 'utf8');
      try {
        t = await vscode.workspace.fs.readFile(vscode.Uri.joinPath(elegida.uri, 'toques.json'));
      } catch { /* esa versión no tenía toques */ }
      await vscode.workspace.fs.writeFile(toquesUri(destGcode), t);
    } catch (e: any) {
      vscode.window.showErrorMessage('G-code: no se pudo cargar — ' + (e?.message || e));
      return;
    }
    trackedUri = destGcode;
    sendRecipe();
    await sendDoc(true);
    vscode.window.showInformationMessage(`G-code: cargada ${elegida.label}`);
  }

  // Cuántos filamentos declara una plantilla, para mostrarlo en la lista.
  //
  // Importa de verdad y no es decoración: el empaquetador copia la lista de
  // filamentos de la plantilla tal cual, así que una pieza con cambios de color
  // empaquetada contra una plantilla de un solo filamento no tiene a qué slot
  // mapear el `T1`, y Bambu Studio ni siquiera ofrece el mapeo de AMS al abrirla.
  function boquillaDe(conf: any): number {
    const n = conf && conf.nozzle_diameter;
    const v = parseFloat(Array.isArray(n) ? n[0] : n);
    return isFinite(v) ? v : 0;
  }

  // Boquilla y ancho de cordón con los que se generó ESTA pieza. Sale de la
  // receta: `--boquilla` si está, y si no el valor por defecto del generador.
  function boquillaDeLaPieza(): number {
    const args: string[] = (receta && receta.args) || [];
    const i = args.indexOf('--boquilla');
    if (i >= 0 && i + 1 < args.length) {
      const v = parseFloat(args[i + 1]);
      if (isFinite(v)) { return v; }
    }
    return receta ? 0.8 : 0;   // el default de lamparas.bowls
  }

  function describirPlantilla(ruta: string): string {
    try {
      const entradas = listZipEntries(fs.readFileSync(ruta));
      const cfg = findEntry(entradas, (n) => n === 'Metadata/project_settings.config');
      if (!cfg) { return 'no parece un proyecto de g-code (sin project_settings)'; }
      const conf = JSON.parse(cfg.data.toString('utf8'));
      const tipos: string[] = conf.filament_type || [];
      // La boquilla va en la misma línea que los filamentos porque es el otro
      // motivo por el que una plantilla no sirve: sus ajustes se copian tal
      // cual, y la impresora rechaza el trabajo si la boquilla declarada no es
      // la que tiene puesta.
      const boq = boquillaDe(conf);
      return `${tipos.length} filamento${tipos.length === 1 ? '' : 's'}: ${tipos.join(', ')}`
        + (boq ? ` · boquilla ${boq}` : '');
    } catch {
      return 'no se pudo leer';
    }
  }

  // Dónde suele instalarse Orca, y Bambu Studio como segunda opción.
  const CANDIDATOS_ORCA: Record<string, string[]> = {
    win32: [
      'C:\\Program Files\\OrcaSlicer\\orca-slicer.exe',
      'C:\\Program Files (x86)\\OrcaSlicer\\orca-slicer.exe',
      `${process.env.LOCALAPPDATA || ''}\\Programs\\OrcaSlicer\\orca-slicer.exe`,
      'C:\\Program Files\\Bambu Studio\\bambu-studio.exe'
    ],
    darwin: [
      '/Applications/OrcaSlicer.app/Contents/MacOS/OrcaSlicer',
      '/Applications/BambuStudio.app/Contents/MacOS/BambuStudio'
    ],
    linux: ['/usr/bin/orca-slicer', '/usr/local/bin/orca-slicer', '/opt/OrcaSlicer/orca-slicer']
  };

  // Encuentra el ejecutable: lo configurado, si no lo autodetectado, si no lo
  // que el usuario elija — y lo guarda para no volver a preguntar.
  //
  // NO hay respaldo con `vscode.env.openExternal`: con un URI `file:` de un
  // .3mf, Windows abre el EXPLORADOR y no el programa, porque .3mf no queda
  // asociado a nada al instalar Orca (`assoc .3mf` vuelve vacío). Parecía que
  // funcionaba y no hacía nada útil.
  async function binarioOrca(): Promise<string | undefined> {
    const cfg = vscode.workspace.getConfiguration('gcodePreview');
    const guardado = cfg.get<string>('orcaBinary') || '';
    if (guardado && fs.existsSync(guardado)) { return guardado; }

    for (const cand of CANDIDATOS_ORCA[process.platform] || []) {
      if (cand && fs.existsSync(cand)) {
        await cfg.update('orcaBinary', cand, vscode.ConfigurationTarget.Global);
        return cand;
      }
    }

    const elegido = await vscode.window.showOpenDialog({
      title: 'Dónde está OrcaSlicer',
      openLabel: 'Usar este',
      canSelectMany: false,
      filters: process.platform === 'win32' ? { Programas: ['exe'] } : undefined
    });
    if (!elegido || !elegido[0]) { return undefined; }
    await cfg.update('orcaBinary', elegido[0].fsPath, vscode.ConfigurationTarget.Global);
    return elegido[0].fsPath;
  }

  // Empaqueta la pieza en un .gcode.3mf y lo abre en OrcaSlicer.
  //
  // No se le pasa el .gcode pelado: Orca es un laminador, espera una malla, y un
  // g-code crudo lo rechaza. El .3mf en cambio ya lleva el toolpath adentro y se
  // abre para revisar y mandar a imprimir. Es el mismo empaquetado que hace
  // "G-code → Bambu 3mf", reusado.
  async function abrirEnOrca() {
    if (!trackedUri) return;
    let destino: vscode.Uri;
    try {
      destino = await vscode.commands.executeCommand('gcodePreview.packBambu3mf', trackedUri, true) as vscode.Uri;
    } catch (e: any) {
      vscode.window.showErrorMessage('G-code: no se pudo empaquetar — ' + (e?.message || e));
      return;
    }
    if (!destino) return;

    const binario = await binarioOrca();
    if (!binario) { return; }
    const cp = require('child_process') as typeof import('child_process');
    const hijo = cp.spawn(binario, [destino.fsPath], { detached: true, stdio: 'ignore' });
    hijo.on('error', (e) => {
      vscode.window.showErrorMessage(`G-code: no se pudo lanzar (${binario}) — ${e.message}`);
    });
    hijo.unref();
  }

  // Reveal the preview for a specific g-code document uri.
  function openPreviewForUri(uri: vscode.Uri) {
    trackedUri = uri;
    ensurePanel();
    panel!.reveal(vscode.ViewColumn.Beside);
    sendDoc();
    sendRecipe();
  }

  const open = vscode.commands.registerCommand('gcodePreview.open', () => {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
      vscode.window.showInformationMessage('Open a .gcode file first, then run this command.');
      return;
    }
    openPreviewForUri(editor.document.uri);
  });
  context.subscriptions.push(open);

  // STL -> Vase-mode G-code, then open it in the preview.
  const slice = vscode.commands.registerCommand('gcodePreview.sliceVase', async () => {
    let stlUri: vscode.Uri | undefined;
    const active = vscode.window.activeTextEditor;
    if (active && active.document.fileName.toLowerCase().endsWith('.stl')) {
      stlUri = active.document.uri;
    } else {
      const picked = await vscode.window.showOpenDialog({
        canSelectMany: false,
        openLabel: 'Slice (vase mode)',
        filters: { STL: ['stl'] }
      });
      stlUri = picked && picked[0];
    }
    if (!stlUri) {
      return;
    }

    try {
      await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'Slicing (vase mode)…' },
        async () => {
          const bytes = await vscode.workspace.fs.readFile(stlUri!);
          const tris = parseStl(bytes);
          if (tris.length === 0) {
            throw new Error('No triangles found in STL.');
          }
          const { gcode, stats } = sliceVase(tris, DEFAULT_OPTIONS);

          const outUri = stlUri!.with({ path: stlUri!.path.replace(/\.stl$/i, '') + '.vase.gcode' });
          await vscode.workspace.fs.writeFile(outUri, Buffer.from(gcode, 'utf8'));

          const doc = await vscode.workspace.openTextDocument(outUri);
          await vscode.window.showTextDocument(doc, { viewColumn: vscode.ViewColumn.One, preview: false });
          openPreviewForUri(outUri);

          vscode.window.showInformationMessage(
            `Vase sliced: ${stats.layers} layers · ${stats.height.toFixed(1)} mm tall · ${stats.triangles} triangles.`
          );
        }
      );
    } catch (err) {
      const m = err instanceof Error ? err.message : String(err);
      vscode.window.showErrorMessage('Vase slicing failed: ' + m);
    }
  });
  context.subscriptions.push(slice);

  // Shared helper: resolve an STL uri from the active editor or a file picker.
  async function resolveStl(label: string): Promise<vscode.Uri | undefined> {
    const active = vscode.window.activeTextEditor;
    if (active && active.document.fileName.toLowerCase().endsWith('.stl')) {
      return active.document.uri;
    }
    const picked = await vscode.window.showOpenDialog({
      canSelectMany: false, openLabel: label, filters: { STL: ['stl'] }
    });
    return picked && picked[0];
  }

  function cfgNum(key: string, dflt: number): number {
    const v = vscode.workspace.getConfiguration('gcodePreview').get<number>(key);
    return typeof v === 'number' ? v : dflt;
  }

  // STL -> overhang-clamped STL. Reshapes bulges/twists so no wall exceeds the
  // target angle from vertical, then writes <name>.fixed.stl for re-slicing.
  async function clampToStl(stlUri: vscode.Uri): Promise<vscode.Uri> {
    const bytes = await vscode.workspace.fs.readFile(stlUri);
    const tris = parseStl(bytes);
    if (tris.length === 0) {
      throw new Error('No triangles found in STL.');
    }
    const maxAngle = cfgNum('clampAngle', 45);
    const layerHeight = cfgNum('layerHeight', 0.3);
    const { stl, stats } = clampOverhangs(tris, { layerHeight, resample: 200, maxAngle });
    const outUri = stlUri.with({ path: stlUri.path.replace(/\.stl$/i, '') + '.fixed.stl' });
    await vscode.workspace.fs.writeFile(outUri, stl);
    vscode.window.showInformationMessage(
      `Overhang clamp @${maxAngle}°: reshaped ${stats.clampedPoints}/${stats.totalPoints} points ` +
      `(max pull ${stats.maxPullMm.toFixed(1)} mm) → ${path.basename(outUri.fsPath)}`
    );
    return outUri;
  }

  const clamp = vscode.commands.registerCommand('gcodePreview.clampOverhangs', async () => {
    const stlUri = await resolveStl('Clamp overhangs');
    if (!stlUri) { return; }
    try {
      await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'Clamping overhangs…' },
        async () => { await clampToStl(stlUri); }
      );
    } catch (err) {
      vscode.window.showErrorMessage('Overhang clamp failed: ' + (err instanceof Error ? err.message : String(err)));
    }
  });
  context.subscriptions.push(clamp);

  // Read Orca config from settings.
  function orcaConfig(): OrcaConfig {
    const c = vscode.workspace.getConfiguration('gcodePreview');
    return {
      binary: c.get<string>('orcaBinary') || '',
      machineSettings: c.get<string>('orcaMachine') || '',
      processSettings: c.get<string>('orcaProcess') || '',
      filament: c.get<string>('orcaFilament') || '',
      extraArgs: c.get<string[]>('orcaExtraArgs') || []
    };
  }

  // Slice an STL with the real OrcaSlicer CLI, extract plain g-code, preview it.
  async function orcaSliceToGcode(stlUri: vscode.Uri): Promise<vscode.Uri> {
    const cfg = orcaConfig();
    if (!cfg.binary) {
      throw new Error('Set "gcodePreview.orcaBinary" (path to the OrcaSlicer executable) in Settings first.');
    }
    const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'orca-'));
    const out3mf = path.join(tmpDir, 'out.gcode.3mf');
    await runOrca(cfg, stlUri.fsPath, out3mf, path.dirname(stlUri.fsPath));
    const zip = await fs.promises.readFile(out3mf);
    const gcode = extractGcodeFrom3mf(zip);
    const outUri = stlUri.with({ path: stlUri.path.replace(/\.stl$/i, '') + '.gcode' });
    await vscode.workspace.fs.writeFile(outUri, Buffer.from(gcode, 'utf8'));
    return outUri;
  }

  const orcaSlice = vscode.commands.registerCommand('gcodePreview.sliceWithOrca', async () => {
    const stlUri = await resolveStl('Slice with Orca');
    if (!stlUri) { return; }
    try {
      await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'Slicing with OrcaSlicer…' },
        async () => {
          const outUri = await orcaSliceToGcode(stlUri);
          openPreviewForUri(outUri);
          vscode.window.showInformationMessage(`Orca sliced → ${path.basename(outUri.fsPath)}`);
        }
      );
    } catch (err) {
      vscode.window.showErrorMessage('Orca slicing failed: ' + (err instanceof Error ? err.message : String(err)));
    }
  });
  context.subscriptions.push(orcaSlice);

  // Full pipeline: STL -> overhang clamp -> Orca slice -> preview overhangs.
  const pipeline = vscode.commands.registerCommand('gcodePreview.pipeline', async () => {
    const stlUri = await resolveStl('Run pipeline');
    if (!stlUri) { return; }
    try {
      await vscode.window.withProgress(
        { location: vscode.ProgressLocation.Notification, title: 'Pipeline: clamp → Orca → preview…' },
        async (p) => {
          p.report({ message: 'clamping overhangs' });
          const fixed = await clampToStl(stlUri);
          p.report({ message: 'slicing with Orca' });
          const outUri = await orcaSliceToGcode(fixed);
          openPreviewForUri(outUri);
        }
      );
    } catch (err) {
      vscode.window.showErrorMessage('Pipeline failed: ' + (err instanceof Error ? err.message : String(err)));
    }
  });
  context.subscriptions.push(pipeline);

  // --- Watching g-code that some external tool keeps rewriting ---------------
  //
  // Two generators feed this: Orca re-exporting over the same path, and the
  // FullControl lamp scripts in ../vacante-g-code, which write a fresh
  // output/<nombre>.gcode on every run. Re-run the generator, see it here.
  //
  // We watch the *directory*, never the file path. fs.watch on a file follows
  // the inode, so a generator that writes a temp file and renames it over the
  // target — the safe way to write, and what guardar_gcode() does — would fire
  // once and then go silent forever. Watching the directory also lets us start
  // before the file exists, which is the normal case for a gitignored output/.
  const GCODE_RE = /\.(gcode|gco|g)$/i;

  function setWatchStatus(label: string | undefined) {
    if (!label) {
      watchStatus?.hide();
      return;
    }
    if (!watchStatus) {
      watchStatus = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
      watchStatus.command = 'gcodePreview.stopWatching';
      watchStatus.tooltip = 'G-code preview is watching for changes — click to stop.';
      context.subscriptions.push(watchStatus);
    }
    watchStatus.text = `$(eye) ${label}`;
    watchStatus.show();
  }

  function stopWatching(quiet = false) {
    if (watcher) { watcher.close(); watcher = undefined; }
    if (watchDebounce) { clearTimeout(watchDebounce); watchDebounce = undefined; }
    watchTarget = undefined;
    watchNewestIn = undefined;
    setWatchStatus(undefined);
    if (!quiet) { vscode.window.showInformationMessage('No longer watching for g-code changes.'); }
  }

  // A generator writing megabytes of g-code fires its first change event long
  // before it has finished. Wait for the size to stop moving so we never parse
  // half a file. Gives up after ~3 s and previews whatever is there.
  async function waitUntilStable(p: string): Promise<boolean> {
    let last = -1;
    for (let i = 0; i < 40; i++) {
      let size: number;
      try {
        size = (await fs.promises.stat(p)).size;
      } catch {
        return false; // vanished mid-write (a rename in progress) — the next event covers it
      }
      if (size > 0 && size === last) { return true; }
      last = size;
      await new Promise((r) => setTimeout(r, 80));
    }
    return true;
  }

  async function newestGcodeIn(dir: string): Promise<string | undefined> {
    let names: string[];
    try {
      names = await fs.promises.readdir(dir);
    } catch {
      return undefined;
    }
    let best: string | undefined;
    let bestTime = -1;
    for (const n of names) {
      if (!GCODE_RE.test(n)) { continue; }
      const full = path.join(dir, n);
      try {
        const st = await fs.promises.stat(full);
        if (st.isFile() && st.mtimeMs > bestTime) { bestTime = st.mtimeMs; best = full; }
      } catch {
        // vanished mid-scan; ignore
      }
    }
    return best;
  }

  async function refreshWatched() {
    const target = watchNewestIn ? await newestGcodeIn(watchNewestIn) : watchTarget;
    if (!target) { return; }
    if (!(await waitUntilStable(target))) { return; }
    trackedUri = vscode.Uri.file(target);
    ensurePanel();
    setWatchStatus(path.basename(target));
    await sendDoc();
  }

  function startWatching(dir: string, opts: { file?: string; newest?: boolean }) {
    stopWatching(true);
    watchTarget = opts.file;
    watchNewestIn = opts.newest ? dir : undefined;
    watcher = fs.watch(dir, (_event, filename) => {
      const name = filename ? filename.toString() : undefined;
      // `filename` can be null on some platforms — then we can't filter, just refresh.
      if (name) {
        if (watchTarget && path.basename(watchTarget) !== name) { return; }
        if (watchNewestIn && !GCODE_RE.test(name)) { return; }
      }
      if (watchDebounce) { clearTimeout(watchDebounce); }
      watchDebounce = setTimeout(() => { void refreshWatched(); }, 150);
    });
    setWatchStatus(opts.file ? path.basename(opts.file) : `newest in ${path.basename(dir)}/`);
    void refreshWatched();
  }

  context.subscriptions.push({ dispose: () => stopWatching(true) });

  // Watch one g-code file for external rewrites (e.g. Orca re-exporting it).
  const watch = vscode.commands.registerCommand('gcodePreview.watchGcode', async () => {
    let uri: vscode.Uri | undefined;
    const active = vscode.window.activeTextEditor;
    const name = active?.document.fileName.toLowerCase() || '';
    if (name.endsWith('.gcode') || name.endsWith('.gco') || name.endsWith('.g')) {
      uri = active!.document.uri;
    } else {
      const picked = await vscode.window.showOpenDialog({
        canSelectMany: false, openLabel: 'Watch this g-code', filters: { 'G-code': ['gcode', 'gco', 'g'] }
      });
      uri = picked && picked[0];
    }
    if (!uri) { return; }

    openPreviewForUri(uri);
    try {
      startWatching(path.dirname(uri.fsPath), { file: uri.fsPath });
      vscode.window.showInformationMessage(
        `Watching ${path.basename(uri.fsPath)} — exports over this file refresh the preview automatically.`
      );
    } catch (err) {
      vscode.window.showErrorMessage('Could not watch file: ' + (err instanceof Error ? err.message : String(err)));
    }
  });
  context.subscriptions.push(watch);

  // Watch a whole folder and always preview the newest g-code in it. This is
  // the one for a generator loop: the FullControl scripts write a new file per
  // `--nombre`, so pinning a single path means re-running this command on every
  // rename. The folder need not have any g-code in it yet.
  const watchFolder = vscode.commands.registerCommand('gcodePreview.watchFolder', async (arg?: vscode.Uri) => {
    let dir = arg;
    if (!dir) {
      const picked = await vscode.window.showOpenDialog({
        canSelectMany: false, canSelectFiles: false, canSelectFolders: true,
        openLabel: 'Watch newest g-code here'
      });
      dir = picked && picked[0];
    }
    if (!dir) { return; }

    ensurePanel();
    panel!.reveal(vscode.ViewColumn.Beside);
    try {
      startWatching(dir.fsPath, { newest: true });
      vscode.window.showInformationMessage(
        `Watching ${path.basename(dir.fsPath)}/ — the newest .gcode written there is previewed automatically.`
      );
    } catch (err) {
      vscode.window.showErrorMessage('Could not watch folder: ' + (err instanceof Error ? err.message : String(err)));
    }
  });
  context.subscriptions.push(watchFolder);

  const stopWatch = vscode.commands.registerCommand('gcodePreview.stopWatching', () => stopWatching());
  context.subscriptions.push(stopWatch);

  // Wrap a .gcode in a Bambu .gcode.3mf so it can be printed over LAN — the A1
  // refuses plain g-code, and the Orca CLI has no send/upload option (checked on
  // 2.4.2: "Upload & Print" exists only in the GUI). Needs a template: a real
  // .gcode.3mf the user exported from Orca for their own machine and nozzle.
  // `forzar` ignora la plantilla guardada y vuelve a preguntar. La elección se
  // recuerda porque es por impresora y preguntarla siempre molesta — pero
  // guardarla sin dar forma de cambiarla deja al usuario encerrado con una
  // elección equivocada, que es justo lo que pasó con una plantilla de un solo
  // filamento y una pieza de dos.
  function enviarPlantilla() {
    const r = vscode.workspace.getConfiguration('gcodePreview').get<string>('bambuTemplate') || '';
    panel?.webview.postMessage({
      type: 'plantilla',
      nombre: r ? path.basename(r) : '',
      detalle: r && fs.existsSync(r) ? describirPlantilla(r) : ''
    });
  }

  async function bambuTemplate(forzar = false): Promise<Buffer | undefined> {
    const c = vscode.workspace.getConfiguration('gcodePreview');
    const configured = forzar ? '' : (c.get<string>('bambuTemplate') || '');
    if (configured && fs.existsSync(configured)) {
      return fs.promises.readFile(configured);
    }
    // Antes de esto había un cuadro de "abrir archivo" a secas. Se abría en la
    // última carpeta usada —normalmente `output/`, donde no hay ningún .3mf— y
    // mostraba "ningún elemento coincide", como si la función estuviera rota.
    // Y el repo ya trae varias plantillas. Así que se buscan y se listan.
    const halladas = await vscode.workspace.findFiles('**/*.3mf', '**/node_modules/**', 40);
    const items: (vscode.QuickPickItem & { uri?: vscode.Uri })[] = halladas
      .map((u) => ({
        label: path.basename(u.fsPath),
        description: vscode.workspace.asRelativePath(u),
        detail: describirPlantilla(u.fsPath),
        uri: u
      }))
      .sort((a, b) => a.label.localeCompare(b.label));
    items.push({ label: '$(folder-opened) Elegir otro archivo…' });

    const elegido = items.length > 1
      ? await vscode.window.showQuickPick(items, {
          title: 'Plantilla de impresora (.gcode.3mf exportado de Orca o Bambu Studio)',
          placeHolder: 'De acá salen el start/end g-code y la lista de filamentos'
        })
      : { label: '', uri: undefined };
    if (items.length > 1 && !elegido) { return undefined; }

    let picked: vscode.Uri[] | undefined;
    if (elegido && elegido.uri) {
      picked = [elegido.uri];
    } else {
      picked = await vscode.window.showOpenDialog({
        canSelectMany: false,
        openLabel: 'Use as Bambu template',
        title: 'Pick a .gcode.3mf exported from OrcaSlicer for your printer',
        filters: { 'Bambu g-code project': ['3mf'] }
      });
    }
    if (!picked || !picked[0]) { return undefined; }
    // Remember it: the template is per-printer, not per-file.
    await c.update('bambuTemplate', picked[0].fsPath, vscode.ConfigurationTarget.Global);
    enviarPlantilla();
    return fs.promises.readFile(picked[0].fsPath);
  }

  // Devuelve el URI del .3mf que dejó, para que otros comandos puedan encadenar
  // — el botón "Open in Orca" empaqueta con esto y después abre el resultado.
  // `silencioso` calla el diálogo, que sobra cuando lo llama otro comando.
  const packBambu = vscode.commands.registerCommand('gcodePreview.packBambu3mf', async (arg?: vscode.Uri, silencioso?: boolean) => {
    const src = arg || vscode.window.activeTextEditor?.document.uri;
    if (!src || !GCODE_RE.test(src.fsPath)) {
      vscode.window.showErrorMessage('Open or right-click a .gcode file first.');
      return undefined;
    }
    try {
      let template = await bambuTemplate();
      if (!template) { return undefined; }

      const name = path.basename(src.fsPath).replace(GCODE_RE, '');
      const gcode = await fs.promises.readFile(src.fsPath, 'utf8');

      // ¿Alcanza la plantilla para los slots que usa la pieza? El empaquetador
      // copia la lista de filamentos de la plantilla tal cual, así que un `T1`
      // contra una plantilla de un solo filamento no tiene a qué slot mapear:
      // Bambu Studio abre el archivo sin ofrecer el mapeo de AMS, y el error
      // recién aparece en la impresora. Se avisa acá, que es donde se puede
      // hacer algo.
      const usados = new Set<number>([0]);
      for (const m of gcode.matchAll(/^T([0-3])$/gm)) { usados.add(parseInt(m[1], 10)); }
      const necesarios = Math.max(...usados) + 1;
      // Se reintenta mientras el usuario elija otra plantilla, para que pueda
      // corregir sin salir del flujo ni ir a Settings.
      const boqPieza = boquillaDeLaPieza();
      for (;;) {
        let declarados = 0;
        let boqPlantilla = 0;
        try {
          const cfg = findEntry(listZipEntries(template), (n) => n === 'Metadata/project_settings.config');
          const conf = cfg ? JSON.parse(cfg.data.toString('utf8')) : null;
          declarados = conf ? (conf.filament_type || []).length : 0;
          boqPlantilla = conf ? boquillaDe(conf) : 0;
        } catch { break; }
        const faltanSlots = !!declarados && necesarios > declarados;
        // La boquilla también descalifica una plantilla, y de una forma más
        // dura: los ajustes se copian tal cual, así que una plantilla de 0.4
        // manda un trabajo de 0.4 con extrusiones calculadas para 0.8. La
        // impresora lo rechaza, y si no lo rechazara sería peor.
        const otraBoquilla = !!boqPlantilla && !!boqPieza
          && Math.abs(boqPlantilla - boqPieza) > 0.01;
        if (!faltanSlots && !otraBoquilla) { break; }
        const motivos = [];
        if (faltanSlots) {
          motivos.push(`la pieza usa ${necesarios} filamentos (T0–T${necesarios - 1}) y la plantilla `
            + `declara ${declarados}, así que no va a haber mapeo de AMS`);
        }
        if (otraBoquilla) {
          motivos.push(`la plantilla es de boquilla ${boqPlantilla} y la pieza se generó para `
            + `${boqPieza}: la impresora rechaza el trabajo si no coincide con la que tiene puesta`);
        }
        const seguir = await vscode.window.showWarningMessage(
          'Plantilla: ' + motivos.join('; y ') + '.',
          'Elegir otra plantilla', 'Empaquetar igual', 'Cancelar'
        );
        if (seguir === 'Elegir otra plantilla') {
          const otra = await bambuTemplate(true);
          if (!otra) { return undefined; }
          template = otra;
          continue;
        }
        if (seguir !== 'Empaquetar igual') { return undefined; }
        break;
      }

      const result = packBambu3mf(template, gcode, name);
      const outPath = path.join(path.dirname(src.fsPath), `${name}.gcode.3mf`);
      await fs.promises.writeFile(outPath, result.zip);

      const s = result.stats;
      if (silencioso) { return vscode.Uri.file(outPath); }
      const choice = await vscode.window.showInformationMessage(
        `${name}.gcode.3mf — ${s.layerCount} layers, ${Math.round(s.seconds / 60)} min, ` +
          `${(s.filamentMm / 1000).toFixed(1)} m filament. Open it in Bambu Studio and press Print.`,
        'Reveal in Finder'
      );
      if (choice === 'Reveal in Finder') {
        await vscode.commands.executeCommand('revealFileInOS', vscode.Uri.file(outPath));
      }
      return vscode.Uri.file(outPath);
    } catch (err) {
      vscode.window.showErrorMessage('Could not pack the .gcode.3mf: ' + (err instanceof Error ? err.message : String(err)));
      return undefined;
    }
  });
  context.subscriptions.push(packBambu);

  // Para cambiarla cuando no estás en el medio de empaquetar.
  context.subscriptions.push(
    vscode.commands.registerCommand('gcodePreview.pickBambuTemplate', async () => {
      const t = await bambuTemplate(true);
      if (t) {
        const r = vscode.workspace.getConfiguration('gcodePreview').get<string>('bambuTemplate');
        vscode.window.showInformationMessage('G-code: plantilla → ' + path.basename(r || ''));
      }
    })
  );

  // Hot reload on save.
  context.subscriptions.push(
    vscode.workspace.onDidSaveTextDocument((doc) => {
      if (trackedUri && doc.uri.toString() === trackedUri.toString()) {
        sendDoc();
      }
    })
  );

  // Live update while typing (debounced), so you can scrub the fan bands without saving.
  context.subscriptions.push(
    vscode.workspace.onDidChangeTextDocument((e) => {
      if (trackedUri && e.document.uri.toString() === trackedUri.toString()) {
        if (debounce) {
          clearTimeout(debounce);
        }
        debounce = setTimeout(sendDoc, 300);
      }
    })
  );

  // If you click into a different g-code editor, follow it.
  context.subscriptions.push(
    vscode.window.onDidChangeActiveTextEditor((editor) => {
      if (!panel || !editor) {
        return;
      }
      // While watching, the watcher owns the panel: clicking into some other
      // g-code must not silently retarget it out from under the loop.
      if (watcher) {
        return;
      }
      const name = editor.document.fileName.toLowerCase();
      if (name.endsWith('.gcode') || name.endsWith('.gco') || name.endsWith('.g') || name.endsWith('.nc')) {
        trackedUri = editor.document.uri;
        sendDoc();
      }
    })
  );
}

export function deactivate() {}

function getNonce(): string {
  let text = '';
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  for (let i = 0; i < 32; i++) {
    text += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return text;
}

function getHtml(webview: vscode.Webview, extensionUri: vscode.Uri): string {
  const nonce = getNonce();
  const asset = (...p: string[]) =>
    webview.asWebviewUri(vscode.Uri.joinPath(extensionUri, 'media', ...p));
  // Cache-buster on main.js, keyed to its mtime.
  //
  // The webview caches by URI, and this URI never changed, so editing main.js
  // and reopening the panel could still run the OLD file — which looks exactly
  // like "the extension didn't update" and sends you off reinstalling it for
  // nothing. It matters most when the extension folder is a symlink to a
  // working copy, which is the whole point of the dev loop in the README.
  const versionado = (...p: string[]) => {
    const uri = vscode.Uri.joinPath(extensionUri, 'media', ...p);
    let v = '0';
    try { v = String(fs.statSync(uri.fsPath).mtimeMs | 0); } catch { /* sin mtime, sin cache-buster */ }
    return webview.asWebviewUri(uri).with({ query: 'v=' + v });
  };
  const mainUri = versionado('main.js');
  // Sello de build, visible en el HUD. La pregunta "¿está corriendo el código
  // nuevo?" tiene que poder contestarse de un vistazo; si no, se contesta
  // reinstalando a ciegas, que es como se pierden horas.
  let sello = '?';
  try {
    const pkg = JSON.parse(fs.readFileSync(vscode.Uri.joinPath(extensionUri, 'package.json').fsPath, 'utf8'));
    const m = new Date(fs.statSync(vscode.Uri.joinPath(extensionUri, 'media', 'main.js').fsPath).mtimeMs);
    const dosDigitos = (n: number) => String(n).padStart(2, '0');
    sello = `v${pkg.version} · ${dosDigitos(m.getHours())}:${dosDigitos(m.getMinutes())}`;
  } catch { /* sin sello */ }
  // three.js r128 (global THREE build) + OrbitControls, vendored locally in
  // media/vendor so the preview works offline and needs no remote CSP host.
  const threeUri = asset('vendor', 'three.min.js');
  const orbitUri = asset('vendor', 'OrbitControls.js');
  const csp = [
    `default-src 'none'`,
    `img-src ${webview.cspSource} data:`,
    `style-src ${webview.cspSource} 'unsafe-inline'`,
    `script-src 'nonce-${nonce}'`
  ].join('; ');

  return /* html */ `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="Content-Security-Policy" content="${csp}" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    /* ---------------------------------------------------------------------
       Plano técnico: azul de heliografía, líneas finas y tipografía mono en
       versalitas. Sin esquinas redondeadas ni sombras — un plano se dibuja con
       una sola pluma, y todo lo que parezca "interfaz de app" lo rompe.
       Las cotas y los rótulos van en versalitas espaciadas; los valores, en
       tipo normal, que es donde se apoya la lectura.
       --------------------------------------------------------------------- */
    /* Plano sobre papel, no heliografía: el gris neutro de Orca cansa mucho
       menos en una sesión larga que el azul saturado a pantalla completa, y la
       tinta oscura sobre claro es como se leen los planos de verdad. Los roles
       son los mismos, invertidos. */
    :root {
      --papel: #ebeae7;        /* fondo — el gris de Orca */
      --papel-2: #f7f6f4;      /* relleno de paneles */
      --tinta: #33518f;        /* líneas y texto secundario */
      --tinta-viva: #16264d;   /* valores y títulos */
      --tinta-tenue: #93a3c4;  /* rótulos y bordes */
      --acento: #e8562a;       /* una sola nota cálida, para lo que actúa */
      --mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace;
    }
    html, body { margin: 0; padding: 0; height: 100%; overflow: hidden; background: var(--papel); }
    #c { width: 100vw; height: 100vh; display: block; }

    #hud {
      position: fixed; top: 10px; left: 50%; transform: translateX(-50%);
      font: 10px/1.5 var(--mono); letter-spacing: .08em; text-transform: uppercase;
      color: var(--tinta); pointer-events: none; z-index: 10; white-space: nowrap;
      max-width: calc(100vw - 24px); overflow: hidden; text-overflow: ellipsis;
    }
    #build {
      position: fixed; bottom: 8px; left: 12px; font: 9px/1 var(--mono);
      letter-spacing: .1em; color: var(--tinta-tenue); pointer-events: none; z-index: 10;
    }

    /* --- marco común de los paneles ------------------------------------- */
    #params, #legend {
      background: rgba(247, 246, 244, .94);
      border: 1px solid var(--tinta-tenue);
      color: var(--tinta);
      font: 11px/1.5 var(--mono);
    }

    #legend {
      position: fixed; top: 10px; right: 12px; padding: 8px 10px;
      z-index: 10; text-align: right;
    }
    .sw {
      display: inline-block; width: 8px; height: 8px; margin-right: 6px;
      vertical-align: middle; border: 1px solid rgba(22,38,77,.35);
    }
    #modeBtn, #travelBtn, #solidBtn, #escBtn {
      display: block; width: 100%; margin: 0 0 5px; padding: 4px 10px; cursor: pointer;
      font: 10px/1.4 var(--mono); letter-spacing: .09em; text-transform: uppercase;
      color: var(--tinta-viva); background: transparent;
      border: 1px solid var(--tinta-tenue); border-radius: 0; text-align: left;
    }
    #modeBtn:hover, #travelBtn:hover, #solidBtn:hover, #escBtn:hover {
      background: var(--papel-2); border-color: var(--tinta);
    }

    /* --- panel de parámetros -------------------------------------------- */
    #params {
      position: fixed; top: 10px; left: 12px; width: 272px;
      max-height: calc(100vh - 130px); overflow-y: auto;
      padding: 10px 12px 12px; box-sizing: border-box; z-index: 30;
    }
    #params.hidden { display: none; }
    #params-cab {
      display: flex; justify-content: space-between; align-items: baseline;
      font-size: 10px; letter-spacing: .16em; text-transform: uppercase;
      color: var(--tinta-viva); border-bottom: 1px solid var(--tinta-tenue);
      padding-bottom: 6px; margin-bottom: 9px;
    }
    #params-estado { letter-spacing: .06em; font-size: 9px; color: var(--acento); }

    #receta-btns { display: flex; gap: 6px; margin: 0 0 6px; }
    #receta-btns button, #orcaBtn {
      padding: 5px 0; cursor: pointer; font: 10px/1.3 var(--mono);
      letter-spacing: .12em; text-transform: uppercase;
      color: var(--tinta-viva); background: transparent;
      border: 1px solid var(--tinta-tenue); border-radius: 0;
    }
    #receta-btns button { flex: 1; }
    #orcaBtn {
      display: block; width: 100%; margin: 0 0 10px;
      color: var(--acento); border-color: var(--acento);
    }
    #receta-btns button:hover { background: var(--papel-2); border-color: var(--tinta); }
    #orcaBtn:hover { background: var(--acento); color: var(--papel); }

    /* La plantilla se recuerda entre sesiones, así que sin mostrarla uno queda
       encerrado con la que eligió la primera vez sin saber cuál era. */
    #plantilla {
      margin: -6px 0 10px; padding: 4px 0 0; cursor: pointer;
      font-size: 9px; letter-spacing: .07em; color: var(--tinta-tenue);
      border-top: 1px solid rgba(147,163,196,.55);
      overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
    }
    #plantilla:hover { color: var(--acento); }

    .par-grupo {
      margin: 12px 0 6px; font-size: 9px; letter-spacing: .16em;
      text-transform: uppercase; color: var(--tinta-tenue);
      border-top: 1px solid rgba(147,163,196,.65); padding-top: 7px;
    }
    .par-grupo:first-child { border-top: none; margin-top: 0; padding-top: 0; }
    .par { margin-bottom: 9px; }
    .par-fila {
      display: flex; justify-content: space-between; align-items: baseline;
      font-size: 10px; letter-spacing: .06em; color: var(--tinta);
    }
    .par-fila b { color: var(--tinta-viva); font-weight: 400; font-variant-numeric: tabular-nums; }
    /* Los sliders son cotas: riel de un pixel y un cursor cuadrado, no una
       pastilla — una perilla redonda de app moderna delata el plano. */
    .par input {
      width: 100%; -webkit-appearance: none; appearance: none; height: 1px;
      background: var(--tinta-tenue); outline: none; margin: 7px 0 0; cursor: pointer;
    }
    .par input::-webkit-slider-thumb {
      -webkit-appearance: none; width: 9px; height: 9px; background: var(--papel);
      border: 1px solid var(--tinta-viva); border-radius: 0; cursor: pointer;
    }
    .par input:hover::-webkit-slider-thumb { background: var(--acento); border-color: var(--acento); }

    /* Una corrida del generador tarda segundos y sin nada que lo diga parece
       que el slider no hizo nada. Una raya que barre, no un spinner: es lo que
       dibujaría un plano, y no tapa la pieza. */
    #cargando {
      position: fixed; top: 0; left: 0; right: 0; height: 2px;
      z-index: 40; overflow: hidden; pointer-events: none;
      background: rgba(109, 146, 221, .25);
    }
    #cargando.hidden { display: none; }
    #cargando i {
      display: block; height: 100%; width: 28%;
      background: var(--acento);
      animation: barrer 1.1s cubic-bezier(.65, 0, .35, 1) infinite;
    }
    @keyframes barrer {
      0%   { transform: translateX(-100%); }
      100% { transform: translateX(457%); }
    }

    /* Rótulos de las cotas. Van en DOM y no como textura en la escena: el
       texto de un plano tiene que leerse nítido a cualquier zoom, y una
       etiqueta rasterizada a 9px se deshace en cuanto uno se acerca. */
    .cota {
      position: fixed; z-index: 5; pointer-events: none;
      font: 9px/1 var(--mono); letter-spacing: .12em; text-transform: uppercase;
      color: var(--tinta-viva); background: rgba(247, 246, 244, .88);
      padding: 2px 5px; transform: translate(-50%, -50%); white-space: nowrap;
    }
    .cota.hidden { display: none; }

    /* --- panel de esculpido ---------------------------------------------- */
    #esculpir {
      position: fixed; left: 12px; bottom: 70px; width: 272px;
      max-height: calc(100vh - 420px); overflow-y: auto;
      padding: 10px 12px 12px; box-sizing: border-box; z-index: 30;
      background: rgba(247, 246, 244, .94); border: 1px solid var(--tinta-tenue);
      color: var(--tinta); font: 11px/1.5 var(--mono);
    }
    #esculpir.hidden { display: none; }
    #esc-cab {
      display: flex; justify-content: space-between; align-items: baseline;
      font-size: 10px; letter-spacing: .16em; text-transform: uppercase;
      color: var(--tinta-viva); border-bottom: 1px solid var(--tinta-tenue);
      padding-bottom: 6px; margin-bottom: 9px;
    }
    #esc-estado { letter-spacing: .06em; font-size: 9px; color: var(--acento); }
    /* Sin esto no se sabe si los controles arman el próximo trazo o editan uno
       ya puesto, que son cosas distintas y una de ellas regenera. */
    #esc-titulo {
      margin: -4px 0 8px; font-size: 8.5px; letter-spacing: .16em;
      text-transform: uppercase; color: var(--tinta-tenue);
    }
    /* Un gesto que no se ve en ninguna parte no existe: nadie arrastra al
       costado a ver qué pasa. */
    #esc-gesto {
      margin: -6px 0 9px; padding-bottom: 7px; font-size: 8.5px;
      letter-spacing: .1em; text-transform: uppercase; color: var(--tinta);
      border-bottom: 1px solid rgba(147,163,196,.55);
    }
    #esculpir select {
      width: 100%; margin: 2px 0 8px; padding: 3px 4px; border-radius: 0;
      font: 10px/1.3 var(--mono); letter-spacing: .06em;
      color: var(--tinta-viva); background: var(--papel);
      border: 1px solid var(--tinta-tenue);
    }
    .esc-rot {
      font-size: 9px; letter-spacing: .14em; text-transform: uppercase;
      color: var(--tinta-tenue);
    }
    /* Un aviso no es decoración: es la diferencia entre una pieza y un ovillo. */
    #esc-aviso {
      margin: 4px 0 8px; padding: 6px 7px; font-size: 9.5px; line-height: 1.45;
      color: var(--acento); border: 1px solid var(--acento);
    }
    #esc-aviso.hidden { display: none; }
    #esc-lista { margin-top: 4px; }
    #esc-lista:empty::before {
      content: 'sin toques — clic sobre la pieza y arrastrá'; font-size: 9px;
      letter-spacing: .08em; color: var(--tinta-tenue);
    }
    .esc-toque {
      display: flex; align-items: baseline; gap: 6px; padding: 3px 0;
      border-top: 1px solid rgba(147,163,196,.55); font-size: 9.5px;
    }
    .esc-toque > span:first-child { flex: 1 1 auto; letter-spacing: .04em; }
    .esc-toque b { color: var(--tinta-viva); font-weight: 400; font-variant-numeric: tabular-nums; }
    .esc-toque button {
      flex: 0 0 auto; width: 16px; height: 16px; line-height: 1; padding: 0;
      cursor: pointer; border-radius: 0; background: transparent;
      color: var(--tinta-tenue); border: 1px solid var(--tinta-tenue);
      font: 10px/1 var(--mono);
    }
    .esc-toque button:hover { color: var(--acento); border-color: var(--acento); }
    .esc-toque.sel { color: var(--tinta-viva); }
    #esc-btns { display: flex; gap: 6px; margin-top: 9px; }
    #esc-btns button {
      flex: 1; padding: 5px 0; cursor: pointer; font: 10px/1.3 var(--mono);
      letter-spacing: .12em; text-transform: uppercase; border-radius: 0;
      color: var(--tinta-viva); background: transparent; border: 1px solid var(--tinta-tenue);
    }
    #esc-btns button:hover { background: var(--papel-2); border-color: var(--tinta); }
    #escBtn.on { color: var(--acento); border-color: var(--acento); }

    /* --- barra de reproducción ------------------------------------------ */
    #timebar {
      position: fixed; left: 50%; bottom: 18px; transform: translateX(-50%);
      display: flex; align-items: center; gap: 14px;
      width: min(760px, calc(100vw - 40px));
      padding: 8px 14px; box-sizing: border-box;
      background: rgba(247, 246, 244, .94); border: 1px solid var(--tinta-tenue);
      border-radius: 0; font: 10px/1 var(--mono); letter-spacing: .08em;
      color: var(--tinta); z-index: 20; user-select: none;
    }
    #timebar.hidden { display: none; }
    #play {
      flex: 0 0 auto; width: 26px; height: 26px; border-radius: 0;
      border: 1px solid var(--tinta-tenue); cursor: pointer; background: transparent;
      display: flex; align-items: center; justify-content: center;
    }
    #play:hover { border-color: var(--acento); }
    #play svg { width: 11px; height: 11px; fill: var(--tinta-viva); }
    #scrub {
      flex: 1 1 auto; -webkit-appearance: none; appearance: none;
      height: 1px; background: var(--tinta-tenue); cursor: pointer; outline: none;
    }
    #scrub::-webkit-slider-thumb {
      -webkit-appearance: none; width: 9px; height: 9px; background: var(--papel);
      border: 1px solid var(--tinta-viva); border-radius: 0;
    }
    #tlabel { font-variant-numeric: tabular-nums; white-space: nowrap; }

    /* --- barra de capas -------------------------------------------------- */
    #layerbar {
      position: fixed; right: 14px; top: 50%; transform: translateY(-50%);
      display: flex; flex-direction: column; align-items: center; gap: 8px;
      font: 9px/1.3 var(--mono); letter-spacing: .06em; color: var(--tinta);
      z-index: 20; user-select: none; text-align: center;
    }
    #layerbar.hidden { display: none; }
    #layer {
      -webkit-appearance: none; appearance: none;
      writing-mode: vertical-lr; direction: rtl;
      width: 1px; height: min(46vh, 340px);
      background: var(--tinta-tenue); outline: none; cursor: pointer;
    }
    #layer::-webkit-slider-thumb {
      -webkit-appearance: none; width: 9px; height: 9px; background: var(--papel);
      border: 1px solid var(--tinta-viva); border-radius: 0;
    }
    #layer-top { white-space: pre; }

    /* --- panel angosto ---------------------------------------------------
       El preview vive en una columna de VS Code, no en una ventana: puede
       quedar en 600 px de ancho o en 380 de alto. Con las medidas fijas, el
       panel de parámetros y la leyenda se montaban uno sobre otro y tapaban
       justo la pieza. Se achica lo que se puede y se esconde lo que sobra,
       por orden de importancia: primero el esculpido —que necesita espacio
       para ser usable—, después las filas de detalle de la leyenda. */
    @media (max-width: 900px) {
      #params { width: 208px; padding: 8px 9px 10px; font-size: 10px; }
      #legend { padding: 6px 7px; font-size: 10px; }
      #esculpir { width: 208px; }
      #hud { font-size: 9px; letter-spacing: .05em; }
      #timebar { gap: 8px; padding: 6px 9px; }
      .cota { font-size: 8px; padding: 1px 3px; }
    }
    @media (max-width: 640px) {
      /* Ya no caben las dos columnas: la leyenda pasa a ser solo los botones. */
      #legend > div:not([id]) { display: none; }
      #params, #esculpir { width: 176px; }
      #tlabel { display: none; }
    }
    @media (max-height: 560px) {
      #params { max-height: calc(100vh - 96px); }
      #esculpir { display: none; }        /* esculpir sin altura no se puede usar */
      #layerbar { display: none; }
    }
  </style>
</head>
<body>
  <canvas id="c"></canvas>
  <div id="hud">loading…</div>
  <div id="build">${sello}</div>
  <div id="params" class="hidden">
    <div id="params-cab"><span id="params-tit">Parameters</span><span id="params-estado"></span></div>
    <div id="receta-btns">
      <button id="guardarBtn" title="Guardar esta versión en recetas/ (v001, v002, …)">Save v+</button>
      <button id="cargarBtn" title="Cargar una versión guardada">Load…</button>
    </div>
    <button id="orcaBtn" title="Empaquetar en .gcode.3mf y abrirlo en OrcaSlicer">Open in Orca</button>
    <div id="plantilla" title="La plantilla aporta el start/end g-code, la lista de filamentos y la boquilla. Clic para cambiarla.">—</div>
    <div id="params-lista"></div>
  </div>
  <div id="legend">
    <button id="modeBtn" title="Cycle color scheme: fan → overhang → solape → velocidad → filament → bleed → relief">Color: Fan</button>
    <button id="travelBtn" title="Show or hide travel moves (T)">Travel: shown</button>
    <button id="solidBtn" title="Draw extrusions at real bead thickness (S)">Render: lines</button>
    <button id="escBtn" title="Esculpir (E): clic izquierdo sobre la pieza y arrastrá — arriba/abajo jala o empuja, izquierda/derecha agranda o achica el pincel. Para orbitar: clic derecho, o Shift + clic izquierdo.">Sculpt: off</button>
    <div id="legend-fan">
      <div><span class="sw" style="background:#1f3f8f"></span>fan ON (M106 S255)</div>
      <div><span class="sw" style="background:#e8562a"></span>fan OFF (M107)</div>
      <div><span class="sw" style="background:#a8b2c6"></span>travel move</div>
    </div>
    <div id="legend-ovh" style="display:none">
      <div>overhang (angle from vertical)</div>
      <div><span class="sw" style="background:#146638"></span>0–30° safe</div>
      <div><span class="sw" style="background:#a16207"></span>~45° watch</div>
      <div><span class="sw" style="background:#c2410c"></span>~55° risky</div>
      <div><span class="sw" style="background:#b91c1c"></span>65°+ likely fails</div>
    </div>
    <!-- Lo llena main.js: una fila por escalón, con los mm/s reales. -->
    <div id="legend-vel" style="display:none"></div>
    <div id="legend-sol" style="display:none">
      <div>solape entre vueltas (del ancho del cordón)</div>
      <div><span class="sw" style="background:#157f3c"></span>50%+ apoya bien</div>
      <div><span class="sw" style="background:#a16207"></span>~25% justo</div>
      <div><span class="sw" style="background:#b91c1c"></span>0% no se tocan</div>
    </div>
    <!-- Filled in by main.js: one row per AMS slot the print actually uses. -->
    <div id="legend-fil" style="display:none"></div>
    <div id="legend-bleed" style="display:none">
      <div>colour actually leaving the nozzle</div>
      <div>slot colours, blended by how much</div>
      <div>filament has passed since the change</div>
    </div>
    <div id="legend-rel" style="display:none">
      <div>relief (vs. the layer's mean radius)</div>
      <div><span class="sw" style="background:#c2410c"></span>bulges outward</div>
      <div><span class="sw" style="background:#5a6378"></span>flat wall</div>
      <div><span class="sw" style="background:#0e6f84"></span>cuts inward</div>
    </div>
  </div>
  <div id="cargando" class="hidden"><i></i></div>
  <div id="cota-alto" class="cota hidden"></div>
  <div id="cota-ancho" class="cota hidden"></div>
  <div id="esculpir" class="hidden">
    <div id="esc-cab"><span>Sculpt</span><span id="esc-estado"></span></div>
    <div id="esc-titulo">pincel</div>
    <div id="esc-gesto">↕ fuerza &nbsp; ↔ tamaño &nbsp; · &nbsp; ⇧+izq o der. orbita</div>
    <div id="esc-ctrl"></div>
    <div id="esc-aviso" class="hidden"></div>
    <div id="esc-lista"></div>
    <div id="esc-btns">
      <button id="escDeshacer" title="Quitar el último toque">Undo</button>
      <button id="escLimpiar" title="Quitar todos los toques">Clear</button>
    </div>
  </div>
  <div id="timebar" class="hidden">
    <button id="play" title="Play / pause timelapse (space)">
      <svg id="play-icon" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
    </button>
    <input id="scrub" type="range" min="0" max="1" value="1" step="1" />
    <span id="tlabel">0 / 0</span>
  </div>
  <div id="layerbar" class="hidden">
    <div id="layer-top">–</div>
    <input id="layer" type="range" min="1" max="1" value="1" step="1" title="Layer" />
    <div id="layer-bot">1</div>
  </div>
  <script nonce="${nonce}" src="${threeUri}"></script>
  <script nonce="${nonce}" src="${orbitUri}"></script>
  <script nonce="${nonce}" src="${mainUri}"></script>
</body>
</html>`;
}
