// Vase-mode (spiralize) slicer. Extracts per-layer contours (see contours.ts)
// then emits ONE continuous helical extrusion path where Z ramps up smoothly
// across each loop. No infill, no offsets, no supports.

import { Pt, sliceMeshToLayers } from './contours';

export interface VaseOptions {
  layerHeight: number;   // mm
  lineWidth: number;     // mm
  filamentDia: number;   // mm
  nozzleTemp: number;    // C
  bedTemp: number;       // C
  printSpeed: number;    // mm/s (wall)
  travelSpeed: number;   // mm/s
  firstLayerSpeed: number; // mm/s
  resample: number;      // points per loop
  centerX: number;       // bed X to center the model on
  centerY: number;       // bed Y
}

export const DEFAULT_OPTIONS: VaseOptions = {
  layerHeight: 0.3,
  lineWidth: 0.45,
  filamentDia: 1.75,
  nozzleTemp: 210,
  bedTemp: 60,
  printSpeed: 25,
  travelSpeed: 120,
  firstLayerSpeed: 15,
  resample: 200,
  centerX: 110,
  centerY: 110,
};

export interface SliceStats {
  layers: number;
  height: number;
  triangles: number;
}

export function sliceVase(
  tris: Float32Array,
  opts: VaseOptions = DEFAULT_OPTIONS
): { gcode: string; stats: SliceStats } {
  const triCount = tris.length / 9;
  const L = sliceMeshToLayers(tris, opts.layerHeight, opts.resample);

  // Shift so the model's XY center lands on the bed center.
  const offX = opts.centerX - (L.minX + L.maxX) / 2;
  const offY = opts.centerY - (L.minY + L.maxY) / 2;
  const loops = L.loops.map((loop) => loop.map((p) => ({ x: p.x + offX, y: p.y + offY })));

  const gcode = emitGcode(loops, opts);
  return {
    gcode,
    stats: { layers: loops.length, height: L.maxZ - L.minZ, triangles: triCount },
  };
}

function emitGcode(loops: Pt[][], opts: VaseOptions): string {
  const filArea = Math.PI * (opts.filamentDia / 2) ** 2;
  const efactor = (opts.lineWidth * opts.layerHeight) / filArea; // E per mm XY
  const out: string[] = [];
  const f3 = (v: number) => v.toFixed(3);
  const f5 = (v: number) => v.toFixed(5);

  out.push('; Generated by gcode-preview vase-mode slicer');
  out.push(`; layers=${loops.length} layerHeight=${opts.layerHeight} lineWidth=${opts.lineWidth}`);
  out.push('G90', 'M83');
  out.push(`M140 S${opts.bedTemp}`);
  out.push(`M104 S${opts.nozzleTemp}`);
  out.push(`M190 S${opts.bedTemp}`);
  out.push(`M109 S${opts.nozzleTemp}`);
  out.push('G28', 'G92 E0');

  if (loops.length === 0) {
    out.push('; no printable contours found');
    return out.join('\n') + '\n';
  }

  const zBase = opts.layerHeight;
  const wallF = Math.round(opts.printSpeed * 60);
  const firstF = Math.round(opts.firstLayerSpeed * 60);
  const travelF = Math.round(opts.travelSpeed * 60);

  const first = loops[0][0];
  out.push(`G0 F${travelF} X${f3(first.x)} Y${f3(first.y)} Z${f3(zBase)}`);

  let prev = { x: first.x, y: first.y };
  let fanOn = false;

  for (let li = 0; li < loops.length; li++) {
    const loop = loops[li];
    const n = loop.length;
    const zStart = zBase + li * opts.layerHeight;
    const feed = li === 0 ? firstF : wallF;
    if (li === 1 && !fanOn) { out.push('M106 S255'); fanOn = true; }

    for (let j = 1; j <= n; j++) {
      const p = loop[j % n];
      const z = zStart + (j / n) * opts.layerHeight;
      const dist = Math.hypot(p.x - prev.x, p.y - prev.y);
      const e = dist * efactor;
      const fPart = j === 1 && li === 0 ? ` F${feed}` : '';
      out.push(`G1${fPart} X${f3(p.x)} Y${f3(p.y)} Z${f3(z)} E${f5(e)}`);
      prev = { x: p.x, y: p.y };
    }
  }

  out.push('M107');
  out.push('M104 S0', 'M140 S0');
  out.push('G91', 'G0 Z10 F600', 'G90');
  out.push('M84');
  return out.join('\n') + '\n';
}
